### ISSUE TITLE
Jira option not showing in account creation

### ISSUE THREAD

**Issue by nickkaczmarekwwt** [steamclock/Quests#17]
I thought at one point Jira was an option in the account creation but I don't see it anymore. I see GitHub and gitlab. Did it get removed or am I misremembering that feature?

**Comment by brendanlensink** [comment]
Hey there, sorry to say we no longer support JIRA

**Comment by nickkaczmarekwwt** [comment]
That makes sense. Thanks for the response. If my short usage of JIRA and Bitbucket say anything, it's that I can't blame you.
