### ISSUE TITLE
Something is causing some users on Big Sur to report higher than expected CPU usage for extended periods of time.

### ISSUE THREAD

**Issue by brendanlensink** [steamclock/Quests#5]
We've had a couple support emails about this now from users running Quests on Big Sur reporting higher than expected CP usage, but so far have been unable to reproduce it.

I suspect this might have something to do with users with large numbers of issues/prs getting hung up during decoding, or something else causing requests to retry/fail to decode frequently.

**Comment by brendanlensink** [comment]
Some logs of this happening:
[quests_debug.txt](https://github.com/steamclock/Quests/files/5946524/quests_debug.txt)

It looks like something is causing the get tickets request to fire way more often than it should. Someone mentioned this may be triggered by opening the settings page.

**Comment by brendanlensink** [comment]
I spent some time investigating this more yesterday, and couldn't find a solution but learned a couple things:
- Looking through the logs above, nothing really looks out of place. We suspected that something was causing multiple `getTickets` to fire at the same time, but that doesn't appear to be the case.
- Even though my menu-bar CPU monitor wasn't showing Quests hogging CPU, Activity Monitor was showing it.
- I found some users complaining about Keychain related things causing their CPU usage to spike so I built a version of Quests without Valet (our pod that manages keychain access) and monitored my CPU usage as it runs, but it was still just as bad.

At this point, I'm back to being pretty sure it's something in our process that retrieves tickets from GitHub, etc and turns them into the menu bar. The problem is that the code is pretty complicated, but hasn't changed since Big Sur so I'm not really sure where to start, or why Big Sur suddenly made it bad.

**Comment by brendanlensink** [comment]
More logs from a different user: 
[quests_debug2.txt](https://github.com/steamclock/Quests/files/6124862/quests_debug2.txt)

**Comment by nbrooke** [comment]
I'm on a Big Sur machine finally, so I'll now keep an eye out for this as well. Nothing suspicious so far though. Had Quests running since like noon and it's used 52 seconds of CPU time so far, and currently at 0.0% usage with the occasional "spike" up to 3% usage (presumably when it fetches).

**Comment by samrees** [comment]
If I open quests it immediately takes up 25% CPU and the fans kick on. It never stops. This is configured with Github, I have 3 open issues right now. Deleting and re-setting up my Github personal access token, restarting Quests inbetween does nothing. Uninstalling/Reinstalling the application from the App Store also does nothing.

[quests_debug.txt](https://github.com/steamclock/Quests/files/6509733/quests_debug.txt)
[open_files.txt](https://github.com/steamclock/Quests/files/6509735/open_files.txt)
<img width="819" alt="Screen Shot 2021-05-19 at 10 54 28" src="https://user-images.githubusercontent.com/53450291/118835277-d5668800-b890-11eb-928f-285ad079dcf2.png">
<img width="877" alt="Screen Shot 2021-05-19 at 10 54 08" src="https://user-images.githubusercontent.com/53450291/118835284-d697b500-b890-11eb-9f36-b480c1317bfb.png">
